apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: hive-metastore

resources:
# - mariadb.yaml
- metastore-cfg.yaml
- metastore-deployment.yaml
- metastore-service.yaml