---
apiVersion: v1
kind: Service
metadata:
  name: metastore
spec:
  ports:
  - port: 9083
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        image: hive-metastore
        # env:
        # - name: AWS_ACCESS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-s3-keys
        #       key: access-key
        # - name: AWS_SECRET_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-s3-keys
        #       key: secret-key
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: hive-metastore-site
          mountPath: /opt/hive-metastore/conf/metastore-site.xml
          subPath: metastore-site.xml
        - name: hive-core-site
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        command: ["/opt/hive-metastore/bin/start-metastore"]
        args: ["-p", "9083"]
        resources:
          requests:
            memory: "2G"
            cpu: 1
        imagePullPolicy: Never
      volumes:
        - name: hive-core-site
          configMap:
            name: hive-core-site-cfg
        - name: hive-metastore-site
          configMap:
            name: hive-metastore-site-cfg