apiVersion: v1
kind: ConfigMap
metadata:
  name: tcb-trino-catalog
  labels:
    app: trino
    chart: trino-0.8.0
    release: tcb
    heritage: Helm
    role: catalogs
data:
  lake.properties: |
    connector.name=hive
    hive.metastore.uri=thrift://metastore:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.non-managed-table-writes-enabled=true
    hive.s3select-pushdown.enabled=true
    hive.allow-drop-table=true
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4