apiVersion: v1
kind: ConfigMap
metadata:
  name: tcb-trino-catalog
  labels:
    app: trino
    chart: trino-0.8.0
    release: tcb
    heritage: Helm
    role: catalogs
data:
  iceberg.properties: |
    connector.name=iceberg
    hive.metastore.uri=thrift://metastore:9083
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4