apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: trino-lakehouse

resources:
- configmap-catalog.yaml
- configmap-worker.yaml
- deployment-worker.yaml
- configmap-coordinator.yaml
- deployment-coordinator.yaml
- service.yaml