apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: metastore-db

resources:
- metastore-db-pcv.yaml
- metastore-db-deployment.yaml
- metastore-db-service.yaml