apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore-db
spec:
  selector:
    matchLabels:
      app: metastore-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore-db
    spec:
      containers:
      - name: mariadb
        image: "mariadb/server:latest"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metastore-db-secrets
              key: password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: metastore-for-hive
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "1G"
            cpu: 1
      volumes:
      - name: metastore-for-hive
        persistentVolumeClaim:
          claimName: metastore-db-pv-claim