apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
spec:
  template:
    spec:
      containers:
      - name: hivemeta
        imagePullPolicy: Never
        image: hive-metastore:latest
        command: ["/opt/apache-hive/bin/schematool"]
        args: ["--verbose", "-initSchema", "-dbType", "mysql", "-userName", "root", "-passWord", "secret123321$%", "-url", "jdbc:mysql://metastore-db:3306/metastore_db?createDatabaseIfNotExist=true"]
      restartPolicy: Never
  backoffLimit: 4